// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY34GOawU5yYY_jcM-edvFvq8VmtRun3E',
    appId: '1:154520687325:web:5d38f52f1b1c16ccef0134',
    messagingSenderId: '154520687325',
    projectId: 'uas-mobile-s7',
    authDomain: 'uas-mobile-s7.firebaseapp.com',
    databaseURL: 'https://uas-mobile-s7-default-rtdb.firebaseio.com',
    storageBucket: 'uas-mobile-s7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJZQT-nEeHGcwLPhU5RErYTHuRB0_RK1M',
    appId: '1:154520687325:android:f821111b8823015aef0134',
    messagingSenderId: '154520687325',
    projectId: 'uas-mobile-s7',
    databaseURL: 'https://uas-mobile-s7-default-rtdb.firebaseio.com',
    storageBucket: 'uas-mobile-s7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa7Cx0vjRvD43flaqqpFJ7ya9S_wme-Qo',
    appId: '1:154520687325:ios:e6f9b57a4c60ef02ef0134',
    messagingSenderId: '154520687325',
    projectId: 'uas-mobile-s7',
    databaseURL: 'https://uas-mobile-s7-default-rtdb.firebaseio.com',
    storageBucket: 'uas-mobile-s7.firebasestorage.app',
    iosBundleId: 'com.example.tugasUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa7Cx0vjRvD43flaqqpFJ7ya9S_wme-Qo',
    appId: '1:154520687325:ios:e6f9b57a4c60ef02ef0134',
    messagingSenderId: '154520687325',
    projectId: 'uas-mobile-s7',
    databaseURL: 'https://uas-mobile-s7-default-rtdb.firebaseio.com',
    storageBucket: 'uas-mobile-s7.firebasestorage.app',
    iosBundleId: 'com.example.tugasUas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY34GOawU5yYY_jcM-edvFvq8VmtRun3E',
    appId: '1:154520687325:web:a20e023ea758e290ef0134',
    messagingSenderId: '154520687325',
    projectId: 'uas-mobile-s7',
    authDomain: 'uas-mobile-s7.firebaseapp.com',
    databaseURL: 'https://uas-mobile-s7-default-rtdb.firebaseio.com',
    storageBucket: 'uas-mobile-s7.firebasestorage.app',
  );
}
